# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-jekyll:2.0"
ports: "80:80;4000:4000;4100:4100"

command:
  build:
    - "jekyll build -s /opt/docs -d /var/www/html"

  sass:
    - "sass -t compressed /opt/docs/_sass/theme.scss /opt/docs/assets/theme.css"
  run:

  resize_images:
    - 'find /opt/docs/assets/img -type f -exec mogrify -quality 60 -resize 1000x720^\> {} \;'
    - 'find /opt/docs/assets/user -type f -exec mogrify -quality 60 -resize 1000x720^\> {} \;'

  jekyll: |
    jekyll serve -s /opt/docs -d /var/www/html --drafts --livereload --port 4000 --livereload-port 4100 --host 0.0.0.0

  dev:
    - killall jekyll ||  echo "no job"
    - D:kick jekyll

  killall:
    - killall jekyll
