# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80;4000:4000;4100:4100"

command:
  build:
    - npm install

  dev:
    - "D:npm run watch </dev/zero" # npm won't  work without input on stdin:q

  init-workspaces:
    - "mkdir -p workspaces"
    - "git -C ./workspaces/ clone  git@github.com:kasimirjs/kasi-embed.git"
    - "git -C ./workspaces/ clone  git@github.com:kasimirjs/kasi-elements.git"
    - "npm install"

  killall:
    - killall jekyll
