# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80;4000:4000;4100:4100"

command:
  build:
    - sudo chmod 777 -R /var/www/html
#    - npm install

  dev:
    - killall jekyll ||  echo "no job"
    - D:kick jekyll

  killall:
    - killall jekyll
