# Kickstart container config file - see https://gitub.com/infracamp/kickstart
# Run ./kickstart.sh to start a development-container for this project
version: 1
from: "ghcr.io/nfra-project/kickstart-flavor-php:unstable"
ports: "80:80;4000:4000;4100:4100"

command:
  build:
    - npm install

  dev:
    - "D:npm run watch </dev/zero" # npm won't  work without input on stdin:q

  killall:
    - killall jekyll
